name: Generate Snake

'on':
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: logsbymiii
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FFFFFF&color_dots=%23161B22,%233A3F45,%23666C73,%239AA0A6,%23D1D5DB
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFFFFF&color_dots=%23161B22,%233A3F45,%23666C73,%239AA0A6,%23D1D5DB

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
